# Generated by Django 3.1 on 2020-08-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travel_Logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Logs.location'),
        ),
    ]
